# Generated by Django 4.1.4 on 2023-01-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="environment",
            name="value",
        ),
        migrations.AlterField(
            model_name="environment",
            name="name",
            field=models.CharField(
                choices=[
                    ("dev", "Development"),
                    ("test", "Testing"),
                    ("stage", "Staging"),
                    ("pre_prod", "Pre-production"),
                    ("prod", "Production"),
                    ("live", "Live"),
                ],
                default="dev",
                max_length=8,
                verbose_name="Name",
            ),
        ),
    ]
