# Generated by Django 4.1.4 on 2022-12-27 23:44

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "branch",
                    models.CharField(blank=True, max_length=32, null=True, verbose_name="Branch"),
                ),
                (
                    "tag",
                    models.CharField(blank=True, max_length=32, null=True, verbose_name="Tag"),
                ),
                (
                    "path",
                    models.CharField(blank=True, max_length=64, null=True, verbose_name="Path"),
                ),
                (
                    "token",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sources",
                "ordering": ["-id"],
            },
        ),
    ]
