# Generated by Django 4.1.4 on 2023-01-05 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deployment",
            name="environment",
        ),
    ]
