# Generated by Django 4.1.4 on 2023-01-05 23:00

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "cloud",
                    models.CharField(
                        choices=[
                            ("aws", "Amazon AWS"),
                            ("gcloud", "Google Cloud"),
                            ("acloud", "Azure Cloud"),
                        ],
                        default="aws",
                        max_length=6,
                        verbose_name="Type",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "aws_access_key_id",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
                ),
                (
                    "aws_secret_access_key",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Credentials",
                "ordering": ["-id"],
            },
        ),
    ]
