# Generated by Django 4.1.4 on 2022-12-27 23:44

import django.core.serializers.json
import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Boilerplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "branch",
                    models.CharField(blank=True, max_length=32, null=True, verbose_name="Branch"),
                ),
                (
                    "tag",
                    models.CharField(blank=True, max_length=32, null=True, verbose_name="Tag"),
                ),
                (
                    "path",
                    models.CharField(blank=True, max_length=64, null=True, verbose_name="Path"),
                ),
                (
                    "token",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("iac", "Infrastructure as Code"),
                            ("ci", "Continuous integration"),
                        ],
                        max_length=16,
                        verbose_name="Type",
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        choices=[
                            ("terragrunt", "Terragrunt"),
                            ("gitlab_ci", "Gitlab CI"),
                        ],
                        max_length=16,
                        verbose_name="SubType",
                    ),
                ),
                (
                    "docker_image",
                    models.CharField(max_length=64, verbose_name="Docker Image"),
                ),
                (
                    "docker_command",
                    models.CharField(max_length=64, verbose_name="Docker Command"),
                ),
                (
                    "docker_directory",
                    models.CharField(max_length=32, verbose_name="Docker Directory"),
                ),
                (
                    "inputs",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Inputs",
                    ),
                ),
                (
                    "outputs",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Outputs",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Boilerplates",
                "ordering": ["-id"],
            },
        ),
    ]
