# Generated by Django 4.1.4 on 2023-01-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boilerplates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boilerplate",
            name="docker_command",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Docker Command"),
        ),
        migrations.AlterField(
            model_name="boilerplate",
            name="docker_directory",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="Docker Directory"),
        ),
        migrations.AlterField(
            model_name="boilerplate",
            name="docker_image",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Docker Image"),
        ),
    ]
